import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "./providers/model-provider";
import { ToastContainer } from "react-toastify";
import SessionHeader from "./components/SessionHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <SessionHeader />
        {children}
        <ModalProvider />
        <ToastContainer />
      </body>
    </html>
  );
}
